version: "3"

services:
  db:
    image: postgres:11-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
  api:
    build: api/.
    env_file:
      - django-env.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  app:
    build:
      context: app/.
    volumes:
      - ./app:/code
    ports:
      - "4200:4200"
    command: npm start

volumes:
  database_data:
    driver: local
